workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  
stages:
  - destroy
  - provision

destroy_ec2:
  image: hashicorp/terraform:latest
  stage: destroy
  before_script:
    - terraform --version
    - cd terraform
    - terraform init
  script:
    - terraform destroy -auto-approve
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run on merge requests

terraform_ec2:
  image: hashicorp/terraform:latest
  stage: provision
  before_script:
    - terraform --version
    - cd terraform 
    - terraform init
    - terraform validate
  script:
    - terraform plan
    - terraform apply -auto-approve

