global:
  scrape_interval: 10s 

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: "node-exporter" 
    static_configs: 
      - targets: ["node-exporter:9100"]
  
  - job_name: "cadvisor" 
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: zabbix-node
    static_configs:
      - targets: ['127.0.0.1:9100']

rule_files:
  - "alert.rules"  # Add the path to the file containing your alerting rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'   # Point to your Alertmanager service# Point to your Alertmanager service