apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app   # punem labelu folosit si la podu voting-app-pod.yaml
  template:
    metadata: 
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app   # trebuie sa fie la fel cu labelu din selector: cel de sus sus nu cont
    spec:
      containers:
      - name: voting-app 
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80