version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache 
    volumes:
      - ./apache/conf/proxy.conf:/usr/local/apache2/conf/extra/proxy.conf
      - ./apache/frontend:/usr/local/apache2/htdocs/frontend 
    command: >
      sh -c "echo 'Include conf/extra/proxy.conf' >> /usr/local/apache2/conf/httpd.conf && httpd-foreground"
    ports: 
      - "80:80"
    depends_on:
      - tomcat 
    networks:
      - webapp

  tomcat:
    image: bitnami/tomcat:latest
    container_name: tomcat
    ports:
      - "8080:8080"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - webapp

networks:
  webapp: