apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    targetPort: 80      # portu containerului
    port: 8081          # portu serviciului
    nodePort: 31001     # portu pe care accesam aplicatia din browser
  selector:
    app: result